version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: student
      MYSQL_PASSWORD: logviewer
      MYSQL_ROOT_PASSWORD: root
    ports:
        - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    image: eclipse-temurin:11-jre
    command: java -jar /app/aqa-shop.jar
    volumes:
      - ./artifacts/aqa-shop.jar:/app/aqa-shop.jar
      - ./application.properties:/app/application.properties
    environment:
      SPRING_CONFIG_LOCATION: /app/application.properties
    ports:
      - "8080:8080"
